import { escapeXml } from './epubSanitizer';
import type { EpubCluster } from './epubTypes';

export function buildContainerXml(): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`;
}

export function buildContentOpf(params: {
  title: string;
  language: string;
  uuid: string;
  modifiedDate: string;
  hasBrief: boolean;
  hasOverview: boolean;
  chapterIds: string[];
}): string {
  const { title, language, uuid, modifiedDate, hasBrief, hasOverview, chapterIds } = params;

  const manifestItems: string[] = [
    `<item id="cover" href="cover.xhtml" media-type="application/xhtml+xml"/>`,
    `<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>`,
    `<item id="css" href="styles.css" media-type="text/css"/>`,
  ];
  if (hasOverview) {
    manifestItems.push(`<item id="overview" href="overview.xhtml" media-type="application/xhtml+xml"/>`);
  }
  if (hasBrief) {
    manifestItems.push(`<item id="brief" href="brief.xhtml" media-type="application/xhtml+xml"/>`);
  }
  for (const id of chapterIds) {
    manifestItems.push(`<item id="${id}" href="${id}.xhtml" media-type="application/xhtml+xml"/>`);
  }

  // Spine: cover → overview → brief → nav → chapters
  const spineItems: string[] = [`<itemref idref="cover"/>`];
  if (hasOverview) spineItems.push(`<itemref idref="overview"/>`);
  if (hasBrief) spineItems.push(`<itemref idref="brief"/>`);
  spineItems.push(`<itemref idref="nav"/>`);
  for (const id of chapterIds) spineItems.push(`<itemref idref="${id}"/>`);

  return `<?xml version="1.0" encoding="utf-8"?>
<package version="3.0" xmlns="http://www.idpf.org/2007/opf" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>${escapeXml(title)}</dc:title>
    <dc:language>${language}</dc:language>
    <dc:creator>AI Context Pack</dc:creator>
    <dc:identifier id="bookid">urn:uuid:${uuid}</dc:identifier>
    <meta property="dcterms:modified">${modifiedDate}</meta>
  </metadata>
  <manifest>
    ${manifestItems.join('\n    ')}
  </manifest>
  <spine>
    ${spineItems.join('\n    ')}
  </spine>
</package>`;
}

export function buildCoverXhtml(params: {
  title: string;
  language: string;
  noteCount: number;
  generatedDate: string;
}): string {
  const { title, language, noteCount, generatedDate } = params;
  const isJa = language === 'ja';
  const noteLabel = isJa ? `${noteCount} ノート` : `${noteCount} note${noteCount !== 1 ? 's' : ''}`;
  return `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="${language}">
<head>
  <title>${escapeXml(title)}</title>
  <link rel="stylesheet" type="text/css" href="styles.css"/>
</head>
<body epub:type="cover" xmlns:epub="http://www.idpf.org/2007/ops" class="cover-page">
  <div class="cover-block">
    <h1 class="cover-title">${escapeXml(title)}</h1>
    <p class="cover-byline">Generated by AI Context Pack</p>
    <p class="cover-meta">${escapeXml(noteLabel)} · ${escapeXml(generatedDate)}</p>
  </div>
</body>
</html>`;
}

export function buildOverviewXhtml(params: {
  title: string;
  language: string;
  noteCount: number;
  clusters: EpubCluster[];
}): string {
  const { title, language, noteCount, clusters } = params;
  const isJa = language === 'ja';

  const pageTitle = isJa ? '概要' : 'Overview';
  const mainTopicsLabel = isJa ? '主要トピック' : 'Main Topics';
  const keyNotesLabel = isJa ? '主要ノート' : 'Key Notes';
  const readingOrderLabel = isJa ? '推奨読書順序' : 'Recommended Reading Order';

  const clusterCount = clusters.length;
  const introText = clusterCount > 0
    ? (isJa
        ? `このブックには${noteCount}件のノートが${clusterCount}つのトピックに整理されています。`
        : `This book contains ${noteCount} note${noteCount !== 1 ? 's' : ''} organized into ${clusterCount} topic${clusterCount !== 1 ? 's' : ''}.`)
    : (isJa
        ? `このブックには${noteCount}件のノートが含まれています。`
        : `This book contains ${noteCount} note${noteCount !== 1 ? 's' : ''}.`);

  const body: string[] = [];
  body.push(`<p>${escapeXml(introText)}</p>`);

  if (clusters.length > 0) {
    // Main Topics
    body.push(`<h2>${mainTopicsLabel}</h2>`);
    body.push('<ul>');
    for (const c of clusters) {
      const count = c.chapterIndices.length;
      const suffix = count > 0
        ? (isJa ? `（${count}件）` : ` (${count} note${count !== 1 ? 's' : ''})`)
        : '';
      body.push(`  <li>${escapeXml(c.name)}${suffix}</li>`);
    }
    body.push('</ul>');

    // Key Notes — collect representative notes across all clusters, deduplicated
    const seen = new Set<string>();
    const keyNotes: string[] = [];
    for (const c of clusters) {
      for (const note of c.representativeNotes ?? []) {
        if (!seen.has(note)) {
          seen.add(note);
          keyNotes.push(note);
        }
      }
    }
    if (keyNotes.length > 0) {
      body.push(`<h2>${keyNotesLabel}</h2>`);
      body.push('<ul>');
      for (const note of keyNotes.slice(0, 12)) {
        body.push(`  <li>${escapeXml(note)}</li>`);
      }
      body.push('</ul>');
    }

    // Recommended Reading Order
    body.push(`<h2>${readingOrderLabel}</h2>`);
    body.push('<ol>');
    for (const c of clusters) {
      body.push(`  <li>${escapeXml(c.name)}</li>`);
    }
    body.push('</ol>');
  }

  return `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="${language}">
<head>
  <title>${escapeXml(pageTitle)}</title>
  <link rel="stylesheet" type="text/css" href="styles.css"/>
</head>
<body>
  <h1>${escapeXml(title)}</h1>
  ${body.join('\n  ')}
</body>
</html>`;
}

export function buildNavXhtml(params: {
  title: string;
  language: string;
  hasBrief: boolean;
  hasOverview: boolean;
  chapters: { id: string; title: string }[];
  clusters?: EpubCluster[];
}): string {
  const { title, language, hasBrief, hasOverview, chapters, clusters } = params;
  const isJa = language === 'ja';
  const tocLabel = isJa ? '目次' : 'Table of Contents';
  const prefaceLabel = isJa ? 'まえがき' : 'Preface';
  const coverLabel = isJa ? '表紙' : 'Cover';
  const overviewLabel = isJa ? '概要' : 'Overview';

  const lines: string[] = [];
  lines.push(`    <li><a href="cover.xhtml">${coverLabel}</a></li>`);
  if (hasOverview) {
    lines.push(`    <li><a href="overview.xhtml">${overviewLabel}</a></li>`);
  }
  if (hasBrief) {
    lines.push(`    <li><a href="brief.xhtml">${prefaceLabel}</a></li>`);
  }

  if (clusters && clusters.length > 0) {
    const assignedIndices = new Set<number>();

    for (const cluster of clusters) {
      if (cluster.chapterIndices.length === 0) continue;
      lines.push(`    <li>`);
      lines.push(`      <span>${escapeXml(cluster.name)}</span>`);
      lines.push(`      <ol>`);
      for (const idx of cluster.chapterIndices) {
        const ch = chapters[idx];
        if (!ch) continue;
        assignedIndices.add(idx);
        lines.push(`        <li><a href="${ch.id}.xhtml">${escapeXml(ch.title)}</a></li>`);
      }
      lines.push(`      </ol>`);
      lines.push(`    </li>`);
    }

    const unclustered = chapters.filter((_, i) => !assignedIndices.has(i));
    for (const ch of unclustered) {
      lines.push(`    <li><a href="${ch.id}.xhtml">${escapeXml(ch.title)}</a></li>`);
    }
  } else {
    for (const ch of chapters) {
      lines.push(`    <li><a href="${ch.id}.xhtml">${escapeXml(ch.title)}</a></li>`);
    }
  }

  return `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="${language}">
<head>
  <title>${escapeXml(tocLabel)}</title>
  <link rel="stylesheet" type="text/css" href="styles.css"/>
</head>
<body>
  <nav epub:type="toc" id="toc">
    <h1>${tocLabel}</h1>
    <ol>
${lines.join('\n')}
    </ol>
  </nav>
</body>
</html>`;
}

export function buildChapterXhtml(params: {
  title: string;
  language: string;
  bodyContent: string;
}): string {
  const { title, language, bodyContent } = params;
  return `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="${language}">
<head>
  <title>${escapeXml(title)}</title>
  <link rel="stylesheet" type="text/css" href="styles.css"/>
</head>
<body>
  <h1>${escapeXml(title)}</h1>
  ${bodyContent}
</body>
</html>`;
}

export const EPUB_CSS = `body {
  font-family: serif;
  line-height: 1.6;
  margin: 1em;
}

h1, h2, h3, h4, h5, h6 {
  line-height: 1.3;
  margin-top: 1.2em;
}

p {
  margin: 0.6em 0;
}

pre {
  white-space: pre-wrap;
  overflow-wrap: break-word;
  background: #f4f4f4;
  padding: 0.5em;
  font-size: 0.9em;
}

code {
  font-family: monospace;
  font-size: 0.9em;
}

table {
  border-collapse: collapse;
  width: 100%;
  margin: 0.8em 0;
}

td, th {
  border: 1px solid #999;
  padding: 0.3em 0.5em;
}

th {
  background: #eee;
}

blockquote {
  border-left: 3px solid #ccc;
  margin-left: 1em;
  padding-left: 0.8em;
  color: #555;
}

ul, ol {
  padding-left: 1.5em;
}

li {
  margin: 0.2em 0;
}

hr {
  border: none;
  border-top: 1px solid #ccc;
  margin: 1em 0;
}

/* Cover page */
.cover-page {
  text-align: center;
}

.cover-block {
  margin-top: 30%;
}

.cover-title {
  font-size: 2em;
  font-weight: bold;
  margin-bottom: 0.5em;
  border: none;
}

.cover-byline {
  font-size: 1em;
  color: #666;
  margin: 0.3em 0;
}

.cover-meta {
  font-size: 0.85em;
  color: #999;
  margin-top: 1em;
}
`;
