import { isAiBriefByHeadings, detectIsAiBrief } from '../src/features/ai-brief/brief-moc-generator';

// Headings that appear in a typical AI Brief file
const AI_BRIEF_HEADINGS = ['Topic Clusters', 'Knowledge Map', 'Knowledge Health', 'Open Questions'];

// Headings generated by buildBriefMocContent (knowledge-base mode, no mermaid)
const AI_BRIEF_MOC_HEADINGS = ['Overview', 'Explore by Topic'];

// Headings generated by buildBriefMocContent (knowledge-base mode, with mermaid diagram)
const AI_BRIEF_MOC_WITH_MERMAID_HEADINGS = ['Overview', 'Knowledge Map', 'Explore by Topic'];

// Japanese AI Brief headings
const AI_BRIEF_HEADINGS_JA = ['トピッククラスター', 'ナレッジマップ', 'ナレッジヘルス'];

describe('isAiBriefByHeadings', () => {
  test('returns true when 2 or more AI Brief headings are present', () => {
    expect(isAiBriefByHeadings(AI_BRIEF_HEADINGS)).toBe(true);
  });

  test('returns true for Japanese AI Brief headings', () => {
    expect(isAiBriefByHeadings(AI_BRIEF_HEADINGS_JA)).toBe(true);
  });

  test('returns false for AI Brief MOC headings (no match)', () => {
    expect(isAiBriefByHeadings(AI_BRIEF_MOC_HEADINGS)).toBe(false);
  });

  test('returns false for AI Brief MOC with mermaid (only 1 match: Knowledge Map)', () => {
    expect(isAiBriefByHeadings(AI_BRIEF_MOC_WITH_MERMAID_HEADINGS)).toBe(false);
  });

  test('returns false for regular note headings', () => {
    expect(isAiBriefByHeadings(['Introduction', 'Background', 'Conclusion'])).toBe(false);
  });

  test('returns false for empty headings', () => {
    expect(isAiBriefByHeadings([])).toBe(false);
  });

  test('returns false when only 1 AI Brief heading matches', () => {
    expect(isAiBriefByHeadings(['Topic Clusters', 'Introduction'])).toBe(false);
  });
});

describe('detectIsAiBrief', () => {
  test('returns true for AI Brief file (generatedBy: ai-brief-generator)', () => {
    const fm = { generatedBy: 'ai-brief-generator' };
    expect(detectIsAiBrief(fm, [])).toBe(true);
  });

  test('returns false for AI Brief MOC file (generatedBy: ai-context-pack)', () => {
    // buildBriefMocContent sets both generatedBy: ai-context-pack and sourceType: ai-brief
    const fm = { generatedBy: 'ai-context-pack', sourceType: 'ai-brief' };
    expect(detectIsAiBrief(fm, AI_BRIEF_MOC_HEADINGS)).toBe(false);
  });

  test('returns false for AI Brief MOC even if headings accidentally match', () => {
    // Ensure generatedBy: ai-context-pack takes precedence over headings
    const fm = { generatedBy: 'ai-context-pack', sourceType: 'ai-brief' };
    expect(detectIsAiBrief(fm, AI_BRIEF_HEADINGS)).toBe(false);
  });

  test('returns true for AI Brief file without frontmatter (headings fallback)', () => {
    expect(detectIsAiBrief(undefined, AI_BRIEF_HEADINGS)).toBe(true);
  });

  test('returns false for regular note (no frontmatter, no AI Brief headings)', () => {
    expect(detectIsAiBrief(undefined, ['Introduction', 'Summary'])).toBe(false);
  });

  test('returns false for regular note with null frontmatter', () => {
    expect(detectIsAiBrief(null, [])).toBe(false);
  });

  test('returns false for AI MOC file (generatedBy: ai-context-pack, no sourceType)', () => {
    // Standard AI MOC files generated by buildMocContent also have ai-context-pack
    const fm = { generatedBy: 'ai-context-pack' };
    expect(detectIsAiBrief(fm, [])).toBe(false);
  });
});
